package com.atharok.btremote.domain.entities.remoteInput.keyboard.virtualKeyboard

import com.atharok.btremote.common.utils.KEYBOARD_INPUT_NONE
import com.atharok.btremote.common.utils.getKeyboardReport
import com.atharok.btremote.domain.entities.remoteInput.keyboard.KeyboardKey

class GreekVirtualKeyboardLayout : VirtualKeyboardLayout() {

    protected override val keyboardInputs: Map<Char, ByteArray> by lazy {
        mapOf(
            ' ' to KEYBOARD_KEY_SPACE_BAR,

            '`' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_00.byte),
            '1' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_01.byte),
            '2' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_02.byte),
            '3' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_03.byte),
            '4' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_04.byte),
            '5' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_05.byte),
            '6' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_06.byte),
            '7' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_07.byte),
            '8' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_08.byte),
            '9' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_09.byte),
            '0' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_10.byte),
            '-' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_11.byte),
            '=' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_12.byte),

            ';' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_00.byte),
            'ς' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_01.byte),
            'ε' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_02.byte),
            'ρ' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_03.byte),
            'τ' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_04.byte),
            'υ' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_05.byte),
            'θ' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_06.byte),
            'ι' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_07.byte),
            'ο' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_08.byte),
            'π' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_09.byte),
            '[' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_10.byte),
            ']' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_11.byte),

            'α' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_00.byte),
            'σ' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_01.byte),
            'δ' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_02.byte),
            'φ' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_03.byte),
            'γ' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_04.byte),
            'η' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_05.byte),
            'ξ' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_06.byte),
            'κ' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_07.byte),
            'λ' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_08.byte),
            '´' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_09.byte),
            '\'' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_10.byte),
            '\\' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_11.byte),

            '<' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_00.byte),
            'ζ' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_01.byte),
            'χ' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_02.byte),
            'ψ' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_03.byte),
            'ω' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_04.byte),
            'β' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_05.byte),
            'ν' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_06.byte),
            'μ' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_07.byte),
            ',' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_08.byte),
            '.' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_09.byte),
            '/' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_10.byte),

            // ---- Shift ----

            '~' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_00.byte),
            '!' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_01.byte),
            '@' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_02.byte),
            '#' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_03.byte),
            '$' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_04.byte),
            '%' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_05.byte),
            '^' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_06.byte),
            '&' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_07.byte),
            '*' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_08.byte),
            '(' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_09.byte),
            ')' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_10.byte),
            '_' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_11.byte),
            '+' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_12.byte),

            ':' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_00.byte),
            '΅' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_01.byte),
            'Ε' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_02.byte),
            'Ρ' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_03.byte),
            'Τ' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_04.byte),
            'Υ' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_05.byte),
            'Θ' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_06.byte),
            'Ι' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_07.byte),
            'Ο' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_08.byte),
            'Π' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_09.byte),
            '{' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_10.byte),
            '}' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_11.byte),

            'Α' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_00.byte),
            'Σ' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_01.byte),
            'Δ' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_02.byte),
            'Φ' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_03.byte),
            'Γ' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_04.byte),
            'Η' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_05.byte),
            'Ξ' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_06.byte),
            'Κ' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_07.byte),
            'Λ' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_08.byte),
            '¨' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_09.byte),
            '"' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_10.byte),
            '|' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_11.byte),

            '>' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_00.byte),
            'Ζ' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_01.byte),
            'Χ' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_02.byte),
            'Ψ' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_03.byte),
            'Ω' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_04.byte),
            'Β' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_05.byte),
            'Ν' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_06.byte),
            'Μ' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_07.byte),
            '?' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_10.byte),

            // ---- Alt Gr ----

            '²' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_02.byte),
            '³' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_03.byte),
            '£' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_04.byte),
            '§' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_05.byte),
            '¶' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_06.byte),
            '¤' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_08.byte),
            '¦' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_09.byte),
            '°' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_10.byte),
            '±' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_11.byte),
            '½' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_12.byte),

            '€' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_02.byte),
            '®' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_03.byte),
            '¥' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_05.byte),
            '«' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_10.byte),
            '»' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_11.byte),

            '¬' to getKeyboardReport(0x40, KeyboardKey.ROW_3_KEY_11.byte),

            '©' to getKeyboardReport(0x40, KeyboardKey.ROW_4_KEY_03.byte),

            // ---- Shift + Alt Gr ----

        )
    }

    protected override val extraInputs: Map<Char, ByteArray> by lazy {
        mapOf(
            '¹' to (keyboardInputs['1'] ?: KEYBOARD_INPUT_NONE),
            'µ' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            '¢' to (keyboardInputs['c'] ?: KEYBOARD_INPUT_NONE),

            'À' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Á' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Â' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Ã' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Ä' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Å' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Ą' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Æ' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Ç' to (keyboardInputs['C'] ?: KEYBOARD_INPUT_NONE),
            'Č' to (keyboardInputs['C'] ?: KEYBOARD_INPUT_NONE),
            'Ć' to (keyboardInputs['C'] ?: KEYBOARD_INPUT_NONE),
            'È' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'É' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ê' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ë' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ě' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ę' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ì' to (keyboardInputs['I'] ?: KEYBOARD_INPUT_NONE),
            'Í' to (keyboardInputs['I'] ?: KEYBOARD_INPUT_NONE),
            'Î' to (keyboardInputs['I'] ?: KEYBOARD_INPUT_NONE),
            'Ï' to (keyboardInputs['I'] ?: KEYBOARD_INPUT_NONE),
            'Ł' to (keyboardInputs['L'] ?: KEYBOARD_INPUT_NONE),
            'Ñ' to (keyboardInputs['N'] ?: KEYBOARD_INPUT_NONE),
            'Ń' to (keyboardInputs['N'] ?: KEYBOARD_INPUT_NONE),
            'Ò' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Ó' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Ô' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Õ' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Ö' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            '×' to (keyboardInputs['x'] ?: KEYBOARD_INPUT_NONE),
            'Ø' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Ř' to (keyboardInputs['R'] ?: KEYBOARD_INPUT_NONE),
            'Š' to (keyboardInputs['S'] ?: KEYBOARD_INPUT_NONE),
            'Ś' to (keyboardInputs['S'] ?: KEYBOARD_INPUT_NONE),
            'Ù' to (keyboardInputs['U'] ?: KEYBOARD_INPUT_NONE),
            'Ú' to (keyboardInputs['U'] ?: KEYBOARD_INPUT_NONE),
            'Û' to (keyboardInputs['U'] ?: KEYBOARD_INPUT_NONE),
            'Ü' to (keyboardInputs['U'] ?: KEYBOARD_INPUT_NONE),
            'Ẃ' to (keyboardInputs['W'] ?: KEYBOARD_INPUT_NONE),
            'Ý' to (keyboardInputs['Y'] ?: KEYBOARD_INPUT_NONE),
            'Ž' to (keyboardInputs['Z'] ?: KEYBOARD_INPUT_NONE),
            'Ż' to (keyboardInputs['Z'] ?: KEYBOARD_INPUT_NONE),
            'Ź' to (keyboardInputs['Z'] ?: KEYBOARD_INPUT_NONE),

            'à' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'á' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'â' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'ã' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'ä' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'å' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'ą' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'æ' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'ç' to (keyboardInputs['c'] ?: KEYBOARD_INPUT_NONE),
            'č' to (keyboardInputs['c'] ?: KEYBOARD_INPUT_NONE),
            'ć' to (keyboardInputs['c'] ?: KEYBOARD_INPUT_NONE),
            'è' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'é' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ê' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ë' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ě' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ę' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ì' to (keyboardInputs['i'] ?: KEYBOARD_INPUT_NONE),
            'í' to (keyboardInputs['i'] ?: KEYBOARD_INPUT_NONE),
            'î' to (keyboardInputs['i'] ?: KEYBOARD_INPUT_NONE),
            'ï' to (keyboardInputs['i'] ?: KEYBOARD_INPUT_NONE),
            'ł' to (keyboardInputs['l'] ?: KEYBOARD_INPUT_NONE),
            'ñ' to (keyboardInputs['n'] ?: KEYBOARD_INPUT_NONE),
            'ń' to (keyboardInputs['n'] ?: KEYBOARD_INPUT_NONE),
            'ò' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'ó' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'ô' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'õ' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'ö' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            '÷' to (keyboardInputs['/'] ?: KEYBOARD_INPUT_NONE),
            'ø' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'ř' to (keyboardInputs['r'] ?: KEYBOARD_INPUT_NONE),
            'š' to (keyboardInputs['s'] ?: KEYBOARD_INPUT_NONE),
            'ś' to (keyboardInputs['s'] ?: KEYBOARD_INPUT_NONE),
            'ù' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            'ú' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            'û' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            'ü' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            'ẃ' to (keyboardInputs['w'] ?: KEYBOARD_INPUT_NONE),
            'ý' to (keyboardInputs['y'] ?: KEYBOARD_INPUT_NONE),
            'ÿ' to (keyboardInputs['y'] ?: KEYBOARD_INPUT_NONE),
            'ž' to (keyboardInputs['z'] ?: KEYBOARD_INPUT_NONE),
            'ż' to (keyboardInputs['z'] ?: KEYBOARD_INPUT_NONE),
            'ź' to (keyboardInputs['z'] ?: KEYBOARD_INPUT_NONE)
        )
    }
}