package com.atharok.btremote.domain.entities.remoteInput.keyboard.virtualKeyboard

import com.atharok.btremote.common.utils.KEYBOARD_INPUT_NONE
import com.atharok.btremote.common.utils.getKeyboardReport
import com.atharok.btremote.domain.entities.remoteInput.keyboard.KeyboardKey

class PortugueseVirtualKeyboardLayout : VirtualKeyboardLayout() {

    protected override val keyboardInputs: Map<Char, ByteArray> by lazy {
        mapOf(
            ' ' to KEYBOARD_KEY_SPACE_BAR,

            '\\' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_00.byte),
            '1' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_01.byte),
            '2' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_02.byte),
            '3' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_03.byte),
            '4' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_04.byte),
            '5' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_05.byte),
            '6' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_06.byte),
            '7' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_07.byte),
            '8' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_08.byte),
            '9' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_09.byte),
            '0' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_10.byte),
            '\'' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_11.byte),
            '«' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_12.byte),

            'q' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_00.byte),
            'w' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_01.byte),
            'e' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_02.byte),
            'r' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_03.byte),
            't' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_04.byte),
            'y' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_05.byte),
            'u' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_06.byte),
            'i' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_07.byte),
            'o' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_08.byte),
            'p' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_09.byte),
            '+' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_10.byte),
            '´' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_11.byte),

            'a' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_00.byte),
            's' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_01.byte),
            'd' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_02.byte),
            'f' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_03.byte),
            'g' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_04.byte),
            'h' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_05.byte),
            'j' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_06.byte),
            'k' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_07.byte),
            'l' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_08.byte),
            'ç' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_09.byte),
            'º' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_10.byte),
            '˜' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_11.byte),

            '<' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_00.byte),
            'z' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_01.byte),
            'x' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_02.byte),
            'c' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_03.byte),
            'v' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_04.byte),
            'b' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_05.byte),
            'n' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_06.byte),
            'm' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_07.byte),
            ',' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_08.byte),
            '.' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_09.byte),
            '-' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_10.byte),

            // ---- Shift ----

            '|' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_00.byte),
            '!' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_01.byte),
            '"' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_02.byte),
            '#' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_03.byte),
            '$' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_04.byte),
            '%' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_05.byte),
            '&' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_06.byte),
            '/' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_07.byte),
            '(' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_08.byte),
            ')' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_09.byte),
            '=' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_10.byte),
            '?' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_11.byte),
            '»' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_12.byte),

            'Q' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_00.byte),
            'W' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_01.byte),
            'E' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_02.byte),
            'R' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_03.byte),
            'T' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_04.byte),
            'Y' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_05.byte),
            'U' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_06.byte),
            'I' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_07.byte),
            'O' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_08.byte),
            'P' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_09.byte),
            '*' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_10.byte),
            'ˋ' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_11.byte),

            'A' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_00.byte),
            'S' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_01.byte),
            'D' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_02.byte),
            'F' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_03.byte),
            'G' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_04.byte),
            'H' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_05.byte),
            'J' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_06.byte),
            'K' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_07.byte),
            'L' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_08.byte),
            'Ç' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_09.byte),
            'ª' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_10.byte),
            'ˆ' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_11.byte),

            '>' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_00.byte),
            'Z' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_01.byte),
            'X' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_02.byte),
            'C' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_03.byte),
            'V' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_04.byte),
            'B' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_05.byte),
            'N' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_06.byte),
            'M' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_07.byte),
            ';' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_08.byte),
            ':' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_09.byte),
            '_' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_10.byte),

            // ---- Alt Gr ----

            '@' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_02.byte),
            '£' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_03.byte),
            '§' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_04.byte),
            '{' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_07.byte),
            '[' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_08.byte),
            ']' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_09.byte),
            '}' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_10.byte),

            '€' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_02.byte)
        )
    }

    protected override val extraInputs: Map<Char, ByteArray> by lazy {
        mapOf(
            '¹' to (keyboardInputs['1'] ?: KEYBOARD_INPUT_NONE),
            '²' to (keyboardInputs['2'] ?: KEYBOARD_INPUT_NONE),
            '³' to (keyboardInputs['3'] ?: KEYBOARD_INPUT_NONE),
            'µ' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            '¥' to (keyboardInputs['Y'] ?: KEYBOARD_INPUT_NONE),
            '¢' to (keyboardInputs['c'] ?: KEYBOARD_INPUT_NONE),

            'À' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Á' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Â' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Ã' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Ä' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Å' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Ą' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Æ' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Č' to (keyboardInputs['C'] ?: KEYBOARD_INPUT_NONE),
            'Ć' to (keyboardInputs['C'] ?: KEYBOARD_INPUT_NONE),
            'È' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'É' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ê' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ë' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ě' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ę' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ì' to (keyboardInputs['I'] ?: KEYBOARD_INPUT_NONE),
            'Í' to (keyboardInputs['I'] ?: KEYBOARD_INPUT_NONE),
            'Î' to (keyboardInputs['I'] ?: KEYBOARD_INPUT_NONE),
            'Ï' to (keyboardInputs['I'] ?: KEYBOARD_INPUT_NONE),
            'Ł' to (keyboardInputs['L'] ?: KEYBOARD_INPUT_NONE),
            'Ñ' to (keyboardInputs['N'] ?: KEYBOARD_INPUT_NONE),
            'Ń' to (keyboardInputs['N'] ?: KEYBOARD_INPUT_NONE),
            'Ò' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Ó' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Ô' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Õ' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Ö' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            '×' to (keyboardInputs['x'] ?: KEYBOARD_INPUT_NONE),
            'Ø' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Ř' to (keyboardInputs['R'] ?: KEYBOARD_INPUT_NONE),
            'Š' to (keyboardInputs['S'] ?: KEYBOARD_INPUT_NONE),
            'Ś' to (keyboardInputs['S'] ?: KEYBOARD_INPUT_NONE),
            'Ù' to (keyboardInputs['U'] ?: KEYBOARD_INPUT_NONE),
            'Ú' to (keyboardInputs['U'] ?: KEYBOARD_INPUT_NONE),
            'Û' to (keyboardInputs['U'] ?: KEYBOARD_INPUT_NONE),
            'Ü' to (keyboardInputs['U'] ?: KEYBOARD_INPUT_NONE),
            'Ẃ' to (keyboardInputs['W'] ?: KEYBOARD_INPUT_NONE),
            'Ý' to (keyboardInputs['Y'] ?: KEYBOARD_INPUT_NONE),
            'Ž' to (keyboardInputs['Z'] ?: KEYBOARD_INPUT_NONE),
            'Ż' to (keyboardInputs['Z'] ?: KEYBOARD_INPUT_NONE),
            'Ź' to (keyboardInputs['Z'] ?: KEYBOARD_INPUT_NONE),

            'à' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'á' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'â' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'ã' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'ä' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'å' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'ą' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'æ' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'č' to (keyboardInputs['c'] ?: KEYBOARD_INPUT_NONE),
            'ć' to (keyboardInputs['c'] ?: KEYBOARD_INPUT_NONE),
            'è' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'é' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ê' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ë' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ě' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ę' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ì' to (keyboardInputs['i'] ?: KEYBOARD_INPUT_NONE),
            'í' to (keyboardInputs['i'] ?: KEYBOARD_INPUT_NONE),
            'î' to (keyboardInputs['i'] ?: KEYBOARD_INPUT_NONE),
            'ï' to (keyboardInputs['i'] ?: KEYBOARD_INPUT_NONE),
            'ł' to (keyboardInputs['l'] ?: KEYBOARD_INPUT_NONE),
            'ñ' to (keyboardInputs['n'] ?: KEYBOARD_INPUT_NONE),
            'ń' to (keyboardInputs['n'] ?: KEYBOARD_INPUT_NONE),
            'ò' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'ó' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'ô' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'õ' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'ö' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            '÷' to (keyboardInputs['/'] ?: KEYBOARD_INPUT_NONE),
            'ø' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'ř' to (keyboardInputs['r'] ?: KEYBOARD_INPUT_NONE),
            'š' to (keyboardInputs['s'] ?: KEYBOARD_INPUT_NONE),
            'ś' to (keyboardInputs['s'] ?: KEYBOARD_INPUT_NONE),
            'ù' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            'ú' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            'û' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            'ü' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            'ẃ' to (keyboardInputs['w'] ?: KEYBOARD_INPUT_NONE),
            'ý' to (keyboardInputs['y'] ?: KEYBOARD_INPUT_NONE),
            'ÿ' to (keyboardInputs['y'] ?: KEYBOARD_INPUT_NONE),
            'ž' to (keyboardInputs['z'] ?: KEYBOARD_INPUT_NONE),
            'ż' to (keyboardInputs['z'] ?: KEYBOARD_INPUT_NONE),
            'ź' to (keyboardInputs['z'] ?: KEYBOARD_INPUT_NONE)
        )
    }
}