package com.atharok.btremote.domain.entities.remoteInput.keyboard.virtualKeyboard

import com.atharok.btremote.common.utils.KEYBOARD_INPUT_NONE
import com.atharok.btremote.common.utils.getKeyboardReport
import com.atharok.btremote.domain.entities.remoteInput.keyboard.KeyboardKey

class UkrainianVirtualKeyboardLayout : VirtualKeyboardLayout() {

    protected override val keyboardInputs: Map<Char, ByteArray> by lazy {
        mapOf(
            ' ' to KEYBOARD_KEY_SPACE_BAR,

            '\'' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_00.byte),
            '1' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_01.byte),
            '2' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_02.byte),
            '3' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_03.byte),
            '4' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_04.byte),
            '5' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_05.byte),
            '6' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_06.byte),
            '7' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_07.byte),
            '8' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_08.byte),
            '9' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_09.byte),
            '0' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_10.byte),
            '-' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_11.byte),
            '=' to getKeyboardReport(0x00, KeyboardKey.ROW_1_KEY_12.byte),

            'й' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_00.byte),
            'ц' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_01.byte),
            'у' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_02.byte),
            'к' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_03.byte),
            'е' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_04.byte),
            'н' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_05.byte),
            'г' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_06.byte),
            'ш' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_07.byte),
            'щ' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_08.byte),
            'з' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_09.byte),
            'х' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_10.byte),
            'ї' to getKeyboardReport(0x00, KeyboardKey.ROW_2_KEY_11.byte),

            'ф' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_00.byte),
            'і' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_01.byte),
            'в' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_02.byte),
            'а' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_03.byte),
            'п' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_04.byte),
            'р' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_05.byte),
            'о' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_06.byte),
            'л' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_07.byte),
            'д' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_08.byte),
            'ж' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_09.byte),
            'є' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_10.byte),
            '\\' to getKeyboardReport(0x00, KeyboardKey.ROW_3_KEY_11.byte),

            'ґ' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_00.byte),
            'я' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_01.byte),
            'ч' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_02.byte),
            'с' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_03.byte),
            'м' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_04.byte),
            'и' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_05.byte),
            'т' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_06.byte),
            'ь' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_07.byte),
            'б' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_08.byte),
            'ю' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_09.byte),
            '.' to getKeyboardReport(0x00, KeyboardKey.ROW_4_KEY_10.byte),

            // ---- Shift ----

            'ʼ' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_00.byte),
            '!' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_01.byte),
            '"' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_02.byte),
            '№' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_03.byte),
            ';' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_04.byte),
            '%' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_05.byte),
            ':' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_06.byte),
            '?' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_07.byte),
            '*' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_08.byte),
            '(' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_09.byte),
            ')' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_10.byte),
            '_' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_11.byte),
            '+' to getKeyboardReport(0x02, KeyboardKey.ROW_1_KEY_12.byte),

            'Й' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_00.byte),
            'Ц' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_01.byte),
            'У' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_02.byte),
            'К' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_03.byte),
            'Е' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_04.byte),
            'Н' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_05.byte),
            'Г' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_06.byte),
            'Ш' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_07.byte),
            'Щ' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_08.byte),
            'З' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_09.byte),
            'Х' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_10.byte),
            'Ї' to getKeyboardReport(0x02, KeyboardKey.ROW_2_KEY_11.byte),

            'Ф' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_00.byte),
            'І' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_01.byte),
            'В' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_02.byte),
            'А' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_03.byte),
            'П' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_04.byte),
            'Р' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_05.byte),
            'О' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_06.byte),
            'Л' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_07.byte),
            'Д' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_08.byte),
            'Ж' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_09.byte),
            'Є' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_10.byte),
            '/' to getKeyboardReport(0x02, KeyboardKey.ROW_3_KEY_11.byte),

            'Ґ' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_00.byte),
            'Я' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_01.byte),
            'Ч' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_02.byte),
            'С' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_03.byte),
            'М' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_04.byte),
            'И' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_05.byte),
            'Т' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_06.byte),
            'Ь' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_07.byte),
            'Б' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_08.byte),
            'Ю' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_09.byte),
            ',' to getKeyboardReport(0x02, KeyboardKey.ROW_4_KEY_10.byte),

            // ---- Alt Gr ----

            '´' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_00.byte),
            '¹' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_01.byte),
            '²' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_02.byte),
            '§' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_03.byte),
            '$' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_04.byte),
            '°' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_05.byte),
            '<' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_06.byte),
            '>' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_07.byte),
            '•' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_08.byte),
            '[' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_09.byte),
            ']' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_10.byte),
            '—' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_11.byte),
            '≠' to getKeyboardReport(0x40, KeyboardKey.ROW_1_KEY_12.byte),

            'ј' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_00.byte),
            'џ' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_01.byte),
            'ў' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_02.byte),
            '®' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_03.byte),
            'ё' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_04.byte),
            'њ' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_05.byte),
            'ґ' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_06.byte),
            'ъ' to getKeyboardReport(0x40, KeyboardKey.ROW_2_KEY_11.byte),

            'ы' to getKeyboardReport(0x40, KeyboardKey.ROW_3_KEY_01.byte),
            'љ' to getKeyboardReport(0x40, KeyboardKey.ROW_3_KEY_07.byte),
            'ђ' to getKeyboardReport(0x40, KeyboardKey.ROW_3_KEY_08.byte),
            //';' to getKeyboardReport(0x40, KeyboardKey.ROW_3_KEY_09.byte),
            'э' to getKeyboardReport(0x40, KeyboardKey.ROW_3_KEY_10.byte),
            //'ґ' to getKeyboardReport(0x40, KeyboardKey.ROW_3_KEY_11.byte),

            //'\\' to getKeyboardReport(0x40, KeyboardKey.ROW_4_KEY_00.byte),
            'ћ' to getKeyboardReport(0x40, KeyboardKey.ROW_4_KEY_02.byte),
            '©' to getKeyboardReport(0x40, KeyboardKey.ROW_4_KEY_03.byte),
            '™' to getKeyboardReport(0x40, KeyboardKey.ROW_4_KEY_06.byte),
            '«' to getKeyboardReport(0x40, KeyboardKey.ROW_4_KEY_08.byte),
            '»' to getKeyboardReport(0x40, KeyboardKey.ROW_4_KEY_09.byte),
            //'/' to getKeyboardReport(0x40, KeyboardKey.ROW_4_KEY_10.byte),

            // ---- Shift + Alt Gr ----

            '~' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_00.byte),
            //'¹' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_01.byte),
            '’' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_02.byte),
            '₴' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_03.byte),
            '€' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_04.byte),
            //'°' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_05.byte),
            //'<' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_06.byte),
            //'>' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_07.byte),
            //'•' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_08.byte),
            '{' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_09.byte),
            '}' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_10.byte),
            '–' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_11.byte),
            '±' to getKeyboardReport(0x42, KeyboardKey.ROW_1_KEY_12.byte),

            'Ј' to getKeyboardReport(0x42, KeyboardKey.ROW_2_KEY_00.byte),
            'Џ' to getKeyboardReport(0x42, KeyboardKey.ROW_2_KEY_01.byte),
            'Ў' to getKeyboardReport(0x42, KeyboardKey.ROW_2_KEY_02.byte),
            //'®' to getKeyboardReport(0x42, KeyboardKey.ROW_2_KEY_03.byte),
            'Ё' to getKeyboardReport(0x42, KeyboardKey.ROW_2_KEY_04.byte),
            'Њ' to getKeyboardReport(0x42, KeyboardKey.ROW_2_KEY_05.byte),
            //'Ґ' to getKeyboardReport(0x42, KeyboardKey.ROW_2_KEY_06.byte),
            'Ъ' to getKeyboardReport(0x42, KeyboardKey.ROW_2_KEY_11.byte),

            'Ы' to getKeyboardReport(0x42, KeyboardKey.ROW_3_KEY_01.byte),
            'Љ' to getKeyboardReport(0x42, KeyboardKey.ROW_3_KEY_07.byte),
            'Ђ' to getKeyboardReport(0x42, KeyboardKey.ROW_3_KEY_08.byte),
            //':' to getKeyboardReport(0x42, KeyboardKey.ROW_3_KEY_09.byte),
            'Э' to getKeyboardReport(0x42, KeyboardKey.ROW_3_KEY_10.byte),
            //'Ґ' to getKeyboardReport(0x42, KeyboardKey.ROW_3_KEY_11.byte),

            '|' to getKeyboardReport(0x42, KeyboardKey.ROW_4_KEY_00.byte),
            'Ћ' to getKeyboardReport(0x42, KeyboardKey.ROW_4_KEY_02.byte),
            //'©' to getKeyboardReport(0x42, KeyboardKey.ROW_4_KEY_03.byte),
            //'™' to getKeyboardReport(0x42, KeyboardKey.ROW_4_KEY_06.byte),
            '„' to getKeyboardReport(0x42, KeyboardKey.ROW_4_KEY_08.byte),
            '“' to getKeyboardReport(0x42, KeyboardKey.ROW_4_KEY_09.byte),
            '…' to getKeyboardReport(0x42, KeyboardKey.ROW_4_KEY_10.byte)
        )
    }

    protected override val extraInputs: Map<Char, ByteArray> by lazy {
        mapOf(
            '³' to (keyboardInputs['3'] ?: KEYBOARD_INPUT_NONE),
            'µ' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            '¥' to (keyboardInputs['Y'] ?: KEYBOARD_INPUT_NONE),
            '¢' to (keyboardInputs['c'] ?: KEYBOARD_INPUT_NONE),

            'À' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Â' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Ã' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Ä' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Å' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Ą' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Æ' to (keyboardInputs['A'] ?: KEYBOARD_INPUT_NONE),
            'Č' to (keyboardInputs['C'] ?: KEYBOARD_INPUT_NONE),
            'Ć' to (keyboardInputs['C'] ?: KEYBOARD_INPUT_NONE),
            'È' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ê' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ë' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ě' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ę' to (keyboardInputs['E'] ?: KEYBOARD_INPUT_NONE),
            'Ì' to (keyboardInputs['I'] ?: KEYBOARD_INPUT_NONE),
            'Î' to (keyboardInputs['I'] ?: KEYBOARD_INPUT_NONE),
            'Ï' to (keyboardInputs['I'] ?: KEYBOARD_INPUT_NONE),
            'Ł' to (keyboardInputs['L'] ?: KEYBOARD_INPUT_NONE),
            'Ñ' to (keyboardInputs['N'] ?: KEYBOARD_INPUT_NONE),
            'Ń' to (keyboardInputs['N'] ?: KEYBOARD_INPUT_NONE),
            'Ò' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Ô' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Õ' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Ö' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            '×' to (keyboardInputs['x'] ?: KEYBOARD_INPUT_NONE),
            'Ø' to (keyboardInputs['O'] ?: KEYBOARD_INPUT_NONE),
            'Ř' to (keyboardInputs['R'] ?: KEYBOARD_INPUT_NONE),
            'Š' to (keyboardInputs['S'] ?: KEYBOARD_INPUT_NONE),
            'Ś' to (keyboardInputs['S'] ?: KEYBOARD_INPUT_NONE),
            'Ù' to (keyboardInputs['U'] ?: KEYBOARD_INPUT_NONE),
            'Û' to (keyboardInputs['U'] ?: KEYBOARD_INPUT_NONE),
            'Ü' to (keyboardInputs['U'] ?: KEYBOARD_INPUT_NONE),
            'Ý' to (keyboardInputs['Y'] ?: KEYBOARD_INPUT_NONE),
            'Ž' to (keyboardInputs['Z'] ?: KEYBOARD_INPUT_NONE),
            'Ż' to (keyboardInputs['Z'] ?: KEYBOARD_INPUT_NONE),
            'Ź' to (keyboardInputs['Z'] ?: KEYBOARD_INPUT_NONE),

            'à' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'â' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'ã' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'ä' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'å' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'ą' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'æ' to (keyboardInputs['a'] ?: KEYBOARD_INPUT_NONE),
            'č' to (keyboardInputs['c'] ?: KEYBOARD_INPUT_NONE),
            'ć' to (keyboardInputs['c'] ?: KEYBOARD_INPUT_NONE),
            'è' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ê' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ë' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ě' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ę' to (keyboardInputs['e'] ?: KEYBOARD_INPUT_NONE),
            'ì' to (keyboardInputs['i'] ?: KEYBOARD_INPUT_NONE),
            'î' to (keyboardInputs['i'] ?: KEYBOARD_INPUT_NONE),
            'ï' to (keyboardInputs['i'] ?: KEYBOARD_INPUT_NONE),
            'ł' to (keyboardInputs['l'] ?: KEYBOARD_INPUT_NONE),
            'ñ' to (keyboardInputs['n'] ?: KEYBOARD_INPUT_NONE),
            'ń' to (keyboardInputs['n'] ?: KEYBOARD_INPUT_NONE),
            'ò' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'ô' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'õ' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'ö' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            '÷' to (keyboardInputs['/'] ?: KEYBOARD_INPUT_NONE),
            'ø' to (keyboardInputs['o'] ?: KEYBOARD_INPUT_NONE),
            'ř' to (keyboardInputs['r'] ?: KEYBOARD_INPUT_NONE),
            'š' to (keyboardInputs['s'] ?: KEYBOARD_INPUT_NONE),
            'ś' to (keyboardInputs['s'] ?: KEYBOARD_INPUT_NONE),
            'ù' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            'û' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            'ü' to (keyboardInputs['u'] ?: KEYBOARD_INPUT_NONE),
            'ý' to (keyboardInputs['y'] ?: KEYBOARD_INPUT_NONE),
            'ÿ' to (keyboardInputs['y'] ?: KEYBOARD_INPUT_NONE),
            'ž' to (keyboardInputs['z'] ?: KEYBOARD_INPUT_NONE),
            'ż' to (keyboardInputs['z'] ?: KEYBOARD_INPUT_NONE),
            'ź' to (keyboardInputs['z'] ?: KEYBOARD_INPUT_NONE)
        )
    }
}